name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: sudo docker build -t ec2-flask:v1.0 -f Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: sudo docker push ${{ secrets.DOCKER_USERNAME }}/ec2-flask:v1.0

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker stop webapp || true
            sudo docker rm webapp || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/ec2-flask:v1.0
            sudo docker run -d -p 80:5000 --name webapp ${{ secrets.DOCKER_USERNAME }}/ec2-flask:v1.0
